### ISSUE TITLE
How can I use a dedicated environment?

### ISSUE THREAD

**Issue by asdf8601** [brpaz/ulauncher-gitlab#11]
Thanks for this amazing extension, it's very useful! 

I'm wondering if there is a way to use a dedicated environment for this instead of installing it in my user path.  I would like to install `python-gitlab` in a environment and using it from there, something like:

```bash
conda create -n ulauncher python=3.6 -y
conda activate ulauncher
pip install python-gitlab  # avoiding --user option
```

**Comment by brpaz** [comment]
Hello.

I think you should probably ask that question in the [Ulauncher](https://github.com/Ulauncher/Ulauncher/) repository.

If you can get Ulauncher to run that way, I guess all the extensions will work.
