### ISSUE TITLE
Does not load suggestions

### ISSUE THREAD

**Issue by tjventurini** [brpaz/ulauncher-gitlab#14]
Just wanted to try out the extension but it is not working out for me :sweat_smile: 

I installed `python-gitlab` and added a personal access token. But it is still just "loading".

Is there anything I missed?  :thinking:

**Comment by marceloarruda01** [comment]
@tjventurini as @brpaz wrote on the read.me you have to install python-gitlab version:

`pip3 install "python-gitlab >=1.5.1,<2.0.0"`

**Comment by tjventurini** [comment]
Hmm... did I really miss that? :thinking:  :sweat_smile: :man_facepalming: 

Thank you for the response, it's working now :+1:
