### ISSUE TITLE
Impossible to access to the functionality

### ISSUE THREAD

**Issue by obarone** [brpaz/ulauncher-gitlab#8]
![image](https://user-images.githubusercontent.com/16206011/84115794-f1319f00-aa2e-11ea-8361-3dc396a9ca69.png)

I have installed gitlab via pip and also todoist, but still impossible to access at the functionality, I double-checked also the token generating a new one with all the privileges, but still not working, am I doing something wrong?

**Comment by Mordreak** [comment]
I have the exact same problem...

**Comment by mvits** [comment]
[](url)
![2020-07-04_18-33](https://user-images.githubusercontent.com/5099573/86522528-f2cf6680-be24-11ea-834f-d7fb1ce42697.png)

Same problem

**Comment by leandromsa** [comment]
Same where any solution to this ?

**Comment by Brblol** [comment]
any solution?

**Comment by Brblol** [comment]
run `pip install python-gitlab then restart Ulauncher

**Comment by mvits** [comment]
@Brblol ,Thanks this solution, the problem is solved
